### ISSUE TITLE
Really interested in this Project

### ISSUE THREAD

**Issue by nosaj66au** [andrei-tatar/node-red-contrib-nora#1]
Hi Andrei,
    This is a great idea and I think I can see where you are going with this project. 
I'm happy to help with any testing if you wish. 
My current Home Automation is all based on Node Red using ESP8266's running Tasmota fimware of which I have about 70 device. All comms are MQTT. 
I have Led 12 volt lighting (100+) most are dimmer-able. Custom 4 gang Wifi wall Switches and Temp/Humidity Sensors for auto fan and heater controls. Solar production and power consumption and currently implementing water metering.  
I have just started looking at Google assistant integration and most option at the moment are messy at best, which is why your project is of interest.

Jason S
Melbourne Australia

**Comment by andrei-tatar** [comment]
@nosaj66au Glad you are interested. 
Send me an email (or your email address) and I will provide you a user and a password to access NORA and begin testing.

**Comment by andrei-tatar** [comment]
@nosaj66au Sent you an email with your testing credentials and info.
