### ISSUE TITLE
Experimental speaker node

### ISSUE THREAD

**Issue by cougarek** [andrei-tatar/node-red-contrib-nora#10]
I think there is problem passing value to speaker node. Nor `volume` or `on` topics doesn't change node state.
![speaker](https://user-images.githubusercontent.com/16385232/54196054-9c684700-44c0-11e9-8cf3-47fc865d05e8.png)

PS: Great project 👍

**Comment by rgerrans** [comment]
Make sure you are setting msg.payload.volume with the volume level and msg.payload.on as a binary true/false.

**Comment by cougarek** [comment]
Thank you, it's working now. My mistake. I used `payload[number],topic:volume` instead of `payload.volume:[number]`.
