### ISSUE TITLE
Google thinks lamps are "offline"

### ISSUE THREAD

**Issue by WouterGritter** [andrei-tatar/node-red-contrib-nora#102]
Since yesterday my lora lamps have been showing as offline in the google app. In node-red the lamps have a red light with the text "Not connected" below them. There are no error messages also.. any idea how I can fix or troubleshoot this?

Thanks

**Comment by hgghyxo** [comment]
Same thing for me too. Tried to reconnect, nothing works. Google home already droped all my devices.
Seems like Node-red cannot connect to NORA service 
![image](https://user-images.githubusercontent.com/8234132/103369483-88913900-4aca-11eb-9595-874155ef3a9d.png)
![image](https://user-images.githubusercontent.com/8234132/103369500-934bce00-4aca-11eb-9af5-7b129825f86c.png)

**Comment by hgghyxo** [comment]
I just found my own problem after posting it above, had problems with my DNS, had to reboot router and server. 
Not sure why, but leaving these here, maybe somebody else finds it useful

**Comment by WouterGritter** [comment]
The issue I was having had to do with my node red instance not being able to communicate with nora over HTTPS. I probably should have done further investigating of the underlying issue, but the quick and dirty fix was to edit the `.node-red/node_modules/node-red-contrib-nora/build/nora.js` file and manually changing `https` to `http`. After a while the issue resolved itself and https worked fine again.

The issue was nothing to do with nora, but I left this here for if somebody else finds it useful too!
