### ISSUE TITLE
Cannot login to NORA homepage

### ISSUE THREAD

**Issue by Roaders** [andrei-tatar/node-red-contrib-nora#108]
Hi All

I am trying to re-create my token for NORA as I am getting the "NORA cannot be reached" error but I am unable to login on the NORA homepage:

https://node-red-google-home.herokuapp.com/login

I have tried both Google and Github accounts. After selecting and authorising my account I am returned to NORA homepage and then get given the `Select Sign in method` option again.

There is a slow post request containing my token that is made to `https://node-red-google-home.herokuapp.com/login` (takes 2.5 seconds) and returns a 302 to redirect me back to to homepage. It seems that this might be timing out.

**Comment by andrei-tatar** [comment]
Hi, 

Unfortunately NORA reached a whooping 2000+ online users and the current implementation and heroku instance can't handle that load.
I'm currently working on a new Firebase based NORA service that will be able to handle thousands of users with ease.

Stay tuned as it's currently in progress.
