### ISSUE TITLE
Unable to access Nora

### ISSUE THREAD

**Issue by jackON5OO** [andrei-tatar/node-red-contrib-nora#110]
Hello Andrei 
I am unable to "regenerated" a new token, I did unlink home assistant, 
I try to login again on the  https://node-red-google-home.herokuapp.com/login
I logged in with my Google account but nothing append the page return back to login after a while
can you help ? 

Thanks Jacques

**Comment by andrei-tatar** [comment]
Unfortunately nora can't handle the load it's under.
I'm working on a new version that will be able to...
Probably a few weeks remaining

**Comment by jackON5OO** [comment]
thanks for quick answer 
I Understand  the success of this nice and easy product,  so Good luck ! We will wait until than
Jacques
