### ISSUE TITLE
transport close

### ISSUE THREAD

**Issue by antistar2011** [andrei-tatar/node-red-contrib-nora#13]
I get every 3 to 10 minutes a message, that nora disconnects and the node shows disconnected.

"nora (d6oPU): disconnected (transport close)" 

node red 0.20.5
node.js 8.15.1
OS ubuntu 18.04 on Vmware 
nora 0.0.23

**Comment by andrei-tatar** [comment]
Can you try outside of vmware. Not sure what's causing the disconnects...

**Comment by antistar2011** [comment]
I tried it on an old  pc with ubuntu... same result

I also made a new key for the service, now the Message is "nora (6RF6w): disconnected (transport close)"
i guess the change is related to the new key.

**Comment by andrei-tatar** [comment]
Are you behind a proxy or something?

**Comment by antistar2011** [comment]
I had a firewall /proxy in front.  Was my first thought, that this could be the case.
I set erverything  on pass through.

this morning  I upgraded node.js to 10.x.

Now 10 hours later still no disconnect

**Comment by andrei-tatar** [comment]
Great!
I will close this issue.
