### ISSUE TITLE
Any plans to open source back end API?

### ISSUE THREAD

**Issue by sriramsv** [andrei-tatar/node-red-contrib-nora#14]
Hello @andrei-tatar ,

I just started using NORA, this is something I have always been looking for or interested in building. Are you looking to open source the backend API so that users will be able to run their own service to hookup to your nodes in Node-Red?. It might help you offload users from your existing heroku instance.

**Comment by andrei-tatar** [comment]
The backend is here https://github.com/andrei-tatar/nora-service . It's been open sourced for a while now.
The idea is that, besides the code, you will also need to publish your own google app, etc.
