### ISSUE TITLE
[Feature] Expose "queryOnlyTemperatureSetting" property on Thermostat

### ISSUE THREAD

**Issue by dprus** [andrei-tatar/node-red-contrib-nora#16]
I have a sensor that is a thermometer and humidity sensor. Obviously this means it's not a thermostat in the traditional sense because it's "ready only". Google's SDK exposes a property that can be set for this exact scenario (queryOnlyTemperatureSetting), however that's not currently exposed by NORA. It would be great if this can be exposed.

This will disallow Google devices from trying to set the temperature on my thermostat, disable respective buttons, etc.

**Comment by andrei-tatar** [comment]
I will have a look. It seems some things changed since this was implemented.

**Comment by andrei-tatar** [comment]
Should be available now in the latest version 0.0.25
