### ISSUE TITLE
Blinds in group different from solo

### ISSUE THREAD

**Issue by CerielRoland** [andrei-tatar/node-red-contrib-nora#19]
Hi there,

If I tell my google home to open the front blinds the percent output is 0.
If I tell my google home to open all the blinds the percent output is 100.
There is a difference in group actions and solo, not sure if it is a nora thing or google home.
Can anyone verify this?

**Comment by andrei-tatar** [comment]
From the nora side of view, I treat it as any other command. Google just sends the `openPercent` value and NORA just forwards the update to node-red. 

https://github.com/andrei-tatar/nora-service/blob/e289be4c570ca7d47ad66f15584755b28afad101/src/http/services/execute.service.ts#L54

I didn't get a chance to also test this but I will have a look but I don't think it's related to NORA.
