### ISSUE TITLE
error after upgrade to 0.0.27 nora-lock.html does not exist

### ISSUE THREAD

**Issue by GravityRZ** [andrei-tatar/node-red-contrib-nora#27]
everything seems to work but i got this error after upgrade from 0.0.24 to 0.0.27

![nora-error](https://user-images.githubusercontent.com/16853535/68996797-42b1eb00-089f-11ea-8d69-b711f3d52014.JPG)

**Comment by rgerrans** [comment]
@GravityRZ That's on me. I was starting to work on locks and accidentally injected part of the code into the last update. I've put in a pull request to @andrei-tatar to fix it.

**Comment by GravityRZ** [comment]
ok thanks. nothing broken as far as i can see so take your time

**Comment by andrei-tatar** [comment]
didn't notice this... I usually install with `npm install`

**Comment by andrei-tatar** [comment]
`0.0.28` published with the fix.

**Comment by GravityRZ** [comment]
tested it
message was still there after upgrade(probably the old message)
after restart everything ok
