### ISSUE TITLE
Registering on the Website

### ISSUE THREAD

**Issue by nosaj66au** [andrei-tatar/node-red-contrib-nora#3]
How do I registering on the website to get a token?

**Comment by Paul-Reed** [comment]
PM Andrei via the node-RED forum.
https://discourse.nodered.org/t/node-red-google-home-integration/4829/14

**Comment by andrei-tatar** [comment]
@nosaj66au It's currently in alpha testing so it's not open yet for registration.

**Comment by andrei-tatar** [comment]
I added support for login using `Google` and `Github` and with this occasion I deleted all the existing user accounts. However, the email address still needs to be added to the Action viewers list for anyone else that wants to use the service.
