### ISSUE TITLE
[feature request] humidity with thermostat

### ISSUE THREAD

**Issue by GravityRZ** [andrei-tatar/node-red-contrib-nora#30]
i noticed the thermostat should have functionality for humidity but it does not work
i feed both msg.payload.temperature and msg.payload.humidity into the thermostat but it does not recognize the humidity value.
I know it should not show in google but when asked it should answer what the humidity is.

In Open Hab i got this working by feeding the temperature in as "CurrentTemperature"
and Humidity as "CurrentHumidity" and grouping those together as a thermostat.
The grouping part was important with OpenHab.

maybe the humidity variable from the nora thermostat is not exposed as CurrentHumidity

**Comment by andrei-tatar** [comment]
If you go to https://node-red-google-home.herokuapp.com/ , can you see the `thermostatHumidityAmbient` property on the thermostat devices you have?

![image](https://user-images.githubusercontent.com/6473183/69011548-5418f700-0974-11ea-9701-9e1c4fa01059.png)

**Comment by GravityRZ** [comment]
yes i can. So does that mean it should work?

`      "type": "thermostat",
      "name": "Temperatuur woonkamer",
      "roomHint": "Woonkamer",
      "availableModes": [
        "off",
        "heatcool",
        "on",
        "eco"
      ],
      "temperatureUnit": "C",
      "state": {
        "online": true,
        "thermostatMode": "heatcool",
        "thermostatTemperatureAmbient": 21.4,
        "thermostatTemperatureSetpoint": 20,
        "thermostatTemperatureSetpointLow": 18,
        "thermostatTemperatureSetpointHigh": 23,
        "thermostatHumidityAmbient": 41
      }`

**Comment by GravityRZ** [comment]
just removed another sensor (which was also holding the humidity) and now it seems to work.

they were called roughly the same so maybe google got confused
