### ISSUE TITLE
sync error, invalid object for sync

### ISSUE THREAD

**Issue by GravityRZ** [andrei-tatar/node-red-contrib-nora#31]
lately i have been playing with temp sensors which are defined as thermostat

everything works but when i change a thermostat setting(eg i enable the heat option) i get this error.
problem is that undoing the thing i did (unselect heat) will not solve the issue.
the only thing to solve is to delete the thermostat, add a new one and put in the old settings

somehow goole does not like it when you change settings on a thermostat which is active

> > msg : string[42]
> "nora: sync error (invalid object for sync)"

**Comment by andrei-tatar** [comment]
Hmm... not sure. Might be a problem in NORA. Though on a resync, the device gets replaced. So it my be an issue at Google.
The json seen here https://node-red-google-home.herokuapp.com/ is what is sent to google.

**Comment by GravityRZ** [comment]
ok next time i have an issue i will see what get's send to google.

not a complete workaround but what helps is if i first take the node offline(deselect nora config)
deploy
then do the changes on the node and deploy again.(node still offline)
then select the right nora config and deploy again so it goes online with the right config

**Comment by GravityRZ** [comment]
closing this one. have not seen it for a while nor the nora reset message
