### ISSUE TITLE
Output status of node

### ISSUE THREAD

**Issue by JaspervanKol** [andrei-tatar/node-red-contrib-nora#35]
Hi @andrei-tatar 

I am using a RF remote and a Arduino to switch on and off wireless sockets. 
Now I am using NORA to switch on and off the wireless sockets with arduino.

The problem I have is when I turn it on with google assistent and then off with the remote but then again turn it on with google assistent it won't turn on because it is still on in google assistent.

It is not possible for me to have feedback from the remote to Node-RED. But is it possible when you ask google to turn something on when it is already on that it will still give the "true" message from the node?

Thank you for this amazing project!

**Comment by andrei-tatar** [comment]
Hi,
Just tick this box in nora-config:

![image](https://user-images.githubusercontent.com/6473183/70449658-08f19000-1aab-11ea-8050-bfd6f3d5a294.png)

**Comment by JaspervanKol** [comment]
Thank you for your quick response.

But unfortunately it doesn't seems to work, I still can't get the second message with the same output state.

Do I need to do something else, like restarting Node-RED?

![image](https://user-images.githubusercontent.com/58696667/70465460-4bbe6280-1ac1-11ea-8963-0ac7de3b40d8.png)

![image](https://user-images.githubusercontent.com/58696667/70465563-80321e80-1ac1-11ea-9f0d-1837e2cf273d.png)

**Comment by andrei-tatar** [comment]
Hmm, don't remember. Try restarting.

**Comment by JaspervanKol** [comment]
Restarting did the trick, It's working now!
