### ISSUE TITLE
Great work - but a need clarification

### ISSUE THREAD

**Issue by nosaj66au** [andrei-tatar/node-red-contrib-nora#4]
Hi Andrei,
      Thanks for the login all works well. I do understand this is the early stage of the project and development is on going. However is there any way to report back a change state from within Node Red?
The use case is:

![image](https://user-images.githubusercontent.com/13111932/49580389-e9f58500-f9a2-11e8-8c9f-7d9f2b838415.png)

Any of the 3 switches can turn Mylight on or off via a on/off/toggle payload. My light feedback reports the current state.
In this case the Physical Switch it does not required feedback however the dashboard switch and hopefully google switch need feed back to understand the present state.

Maybe I just need to look at this a different way?
 
Jason

**Comment by andrei-tatar** [comment]
I think it's fine... Here is how I have it setup:
![image](https://user-images.githubusercontent.com/6473183/49580989-2c926f80-f959-11e8-9660-9e43bc18eb97.png)
The red node is the actual hardware switch. So each change (from switch/google/dashboard) is reported back to the others and vice versa.

**Comment by nosaj66au** [comment]
Cool I'll give it a go. I played around a bit but couldn't quit get the result I was after.Jaon 


Sent from my Samsung GALAXY S5

-------- Original message --------

**Comment by andrei-tatar** [comment]
@nosaj66au Maybe you need to connect the `Physical Switch` output to the inputs of the dashboard and google home nodes.

**Comment by impala454** [comment]
I realize this is closed but I am noticing a similar issue.  I'm using an MQTT topic as a secondary "switch" to the nora light node.  I can't really tie the two together the way @andrei-tatar did above as the MQTT output payload is different than the nora input payload.  [Thumbing through the code](https://github.com/andrei-tatar/node-red-contrib-nora/blob/master/src/nodes/nora-light.ts#L158), it appears I simply need to send a JSON object to the nora node like this (this is actual output from my flow's debug):
```json
{"payload":{"on":true}}
```
This gets sent to the input of the nora light node but my device in google home never updates.  It does update when I toggle the light using the google home app though.  Here is my flow:
<img width="665" alt="nora_flow" src="https://user-images.githubusercontent.com/2024649/74801877-acc29d80-529d-11ea-88a1-31237d91ec11.PNG">
The `GetNoraPayload` function node is just changing the message to match what the nora node is looking for.  Code here:
```javascript
on_off = msg.payload.value;

msg = {};
msg['payload'] = {};
msg.payload['on'] = on_off;

return msg;
```
Any help or thoughts appreciated.  If this works out I'll definitely donate something to the cause!

**Comment by sarreck** [comment]
I have successfully deployed a working version of this. 

The trick was converting the STRING from MQTT to a BOOLEAN state

![image](https://user-images.githubusercontent.com/6550017/74803421-e55f8700-5330-11ea-9b3b-0a1fc5d55f6c.png)

There is a switch to output true/false then they are converted to the Boolean state. Same on the other end. 

I am sure there is a more efficient way to do this, but it works.

**Comment by impala454** [comment]
@sarreck can you show what you're doing in your switch and change nodes?  

I have my MQTT topic input set to output `a parsed JSON object`, so it's definitely not outputting as a string.  I verfied by debug the contents are:: 
```json
{"time":1582090043840,"value":false}
```
I modified the `GetNoraPayload` function to make sure it's outputting what the nora light node needs and here's where it ended up:
```javascript
on = false;

if (msg.payload.value === true) {
    on = true;
}

msg = {};
msg["payload"] = {};
msg.payload.on = on;

return msg;
```
I verified that output with debug here:
```json
{"on":false}
```
Which is what the nora light node says it needs to update state.

**Comment by sarreck** [comment]
Switch
![image](https://user-images.githubusercontent.com/6550017/74819996-5dd83f00-5355-11ea-84ff-f03c411ae175.png)

Change
![image](https://user-images.githubusercontent.com/6550017/74820025-69c40100-5355-11ea-86a6-378bf5f9277b.png)

**Comment by impala454** [comment]
Thanks for this, it made me realize since it's a simple switch (not dimmable or colored) that I just needed to send the raw bool and not the full JSON string.  I also noticed with the switch on the screen under google home it wasn't immediately updating, I just had to refresh it or back out to the previous screen, which is no big deal.  Thanks!
