### ISSUE TITLE
Light node doesn't send the color information for RGB bulbs

### ISSUE THREAD

**Issue by TwinsenLGR** [andrei-tatar/node-red-contrib-nora#40]
Hi Andrei,

I tried to config a light note to command an RGB led band but it seems that the information is not transmitted.
As you can see in the print screen the Light Node contain the information but it transmits only the brightness.

Can you check/help me, please?

![image](https://user-images.githubusercontent.com/10025713/72685622-984f8180-3af4-11ea-99de-d4dfb614da82.png)

**Comment by andrei-tatar** [comment]
Post a minimum json flow that reproduces your issue.

**Comment by andrei-tatar** [comment]
Do you have the "send complete state" checked? Otherwise it only sends the brightness as payload.
![image](https://user-images.githubusercontent.com/6473183/73739771-89510c00-474f-11ea-841b-bdd47e3a9b92.png)

**Comment by TwinsenLGR** [comment]
Thank you, Andrei

The check for the "Send/receive complete state as payload" was the problem. 
Everything is ok now.

The issue can be closed.

P.S. Ai o bere din partea mea :)

**Comment by andrei-tatar** [comment]
> P.S. Ai o bere din partea mea :)
🍻
