### ISSUE TITLE
Pull request for camera device in Nora-service

### ISSUE THREAD

**Issue by realjax** [andrei-tatar/node-red-contrib-nora#42]
Hi Andrei,

I saw that there is a camera trait and thought it would be kinda cool if we could use cheap cameras as security cams and stream them to chromecast devices (and hubs).

Anyway, I created a pull request on nora-service for the inclusion of a camera device. .Could you take a look at that because  I'm not sure if my code is sufficient enough.. It seems a camera device has no state for instance..

More on the camera device is on the google developers pages [here](https://developers.google.com/assistant/smarthome/guides/camera)

Thanks.

**Comment by andrei-tatar** [comment]
This definitely needs more research and I don't have any camera to test with.
Not sure how the camera stream is exposed (if it needs to be exposed - or it works only locally).
I did look a bit over your PR but I don't think it's complete/correct.

**Comment by realjax** [comment]
Basically you could use any cheap chinese camera since almost all of them support ( usually very badly secured) RTSP. I bought [this one](https://nl.aliexpress.com/item/32885045390.html?spm=a2g0s.9042311.0.0.1ec64c4dxA09DD) on aliexpres for around $ 15.  
The RTSP stream could be transformed into an HLS stream relatively easy and that is what a camera device needs.  

The google docs are indeed a little vague and I agree that more research is needed.  I would like to do so but can't get a local copy of the nora service up and running.

**Comment by FireWizard52** [comment]
I have implemented the casting of Camera streams (and also Domoticz webpages) using the Nora Switch node by using CATT (Cast All The Things) and some small scripts.
Full description, you can find at: https://www.domoticz.com/forum/viewtopic.php?f=38&t=30644&p=236032#p236032

**Comment by realjax** [comment]
Thanks. 
I'm not a big fan of having to install and run another service just to get this working more or less so I still think NORA is the way to go.  Nevertheless, I'll check it out.

**Comment by FireWizard52** [comment]
It is using Nora (switch node), but native support would be preferred.
