### ISSUE TITLE
Invert the open/close of blinds? 

### ISSUE THREAD

**Issue by simonbove** [andrei-tatar/node-red-contrib-nora#43]
Hi.

I love your work and just donated to you as well. 

I have a quick question. Would it be possible to invert the open close figures? So 0 becomes 100 and 100 becomes 0? I have ikea blinds with deconz and they are reporting opposite of the Nora plugin. It is not possible to change their behavior, so when I ask them to close they open instead. So a invert option would be highly appreciated.

**Comment by andrei-tatar** [comment]
Added in latest version (0.0.31)
