### ISSUE TITLE
thermostat device invalid state.

### ISSUE THREAD

**Issue by DCandE** [andrei-tatar/node-red-contrib-nora#44]
When I set the thermostat device to query only and one way i receive this error and all devices in the nora flows go offline.

`[warn] nora: sync error (invalid object for sync)

**Comment by zoltantakacshu** [comment]
i had the same issue ... I removed all nodes and recreated them - now all are working fine...

**Comment by andrei-tatar** [comment]
Should be fixed in latest version (0.0.31)
