### ISSUE TITLE
Garage device displays as sensor (not a switch) in Google Home app

### ISSUE THREAD

**Issue by InnesB** [andrei-tatar/node-red-contrib-nora#46]
NORA is working perfectly for me in Node Red, however, Garage device displays as a 'sensor' in the Google Home app (I am using iOS), therefore the app cannot be used to control the garage door. Voice control (e.g. via Google Home Mini) works, and 'manual' true/false inputs to the node also work.

In the iOS app, the garage door sensor icon is displayed as an image of a garage door, with a 'gear' displayed top-right of the image. Touching the icon displays General settings for the device.

I have tried to find some information about this issue, and it appears that around 2 months ago, some users of the commercial 'Moes WiFi Smart Garage Door Opener' report that their icon changed from being a door-opener-switch, to being a sensor icon. I couldn't find any other information relating to this issue. Perhaps Google changed something in the API for this device since it was implemented.

Please let me know if you need further information, or if I can assist with this issue in any way. Thank you.

**Comment by rgerrans** [comment]
Mine have always been that way since I added the device to the binding. I have other devices doing the same thing (I added door locks as well but it hasn't been moved to the main NORA and they are the same) . My Sonos speakers (using Sonos connection) also show up as uncontrollable through the app interface. All three work fine with voice commands. So, I just assumed that was normal behavior, interesting to hear it might be how we implemented it. 

I'll google around a bit this weekend and see if I can learn anything that might be causing it. If you want to share anything you find here as well, we can see if we can figure out what needs to be changed to make them functioning controlls.  @andrei-tatar I'm assuming it's something on the backend services side. Any thoughts?

**Comment by andrei-tatar** [comment]
I think all devices that are "experimental" show up with a gear icon (devices that don't appear in the docs but are supported by Google Home). Not really sure why the garage door would appear like this (since it's in the docs) but as far as I know it's not related to NORA.

**Comment by InnesB** [comment]
Thank you for your responses. I also added 'blinds' device with the same result (blinds appear as sensor with gear icon). I have had trouble finding any information on this 'issue', although I did find some older screenshots of Google Home app showing blinds without the gear icon, so I guess Google must have changed something.

At least we have voice-control over these items; it's just unfortunate that the devices can't be controlled from within the Google Home app.

On a side-note, I also noticed that the Google Home in-app controls do not reflect the state of the device (e.g. lightswitch does not indicate on or off); one has to click the control to see the device page in order to determine its state, which seems odd to me. Apple Homekit allows control of devices by tapping /swiping the control and shows the state, so Google are somewhat behind (in my opinion). However, I do understand that this is outside the control of 3rd party developers. Thank you for your work on this project; it is much appreciated.

I will close this issue as no further action is possible at this stage.

**Comment by rgerrans** [comment]
@InnesB Found this. Garage Doors aren't supported for Touch Controls - https://developers.google.com/assistant/smarthome/develop/touch-controls#supported_device_types

**Comment by InnesB** [comment]
@rgerrans Thanks for this link, and for your time on this issue.  Some of these are puzzling; for example, it would seem logical that a blind that can be set as a percentage (open/closed) would require a sliding touch control (as is the case with Apple Homekit). However, we are in the hands of Google, and will just have to hope that they update these devices.

**Comment by Jeroen-H** [comment]
Hi, thanks for the research. Almost went mental on this :smile: 

I found the following url, you can submit a request there. Hopefully if we submit enough..

https://developers.google.com/assistant/smarthome/support

Kind regards
