### ISSUE TITLE
remove devices

### ISSUE THREAD

**Issue by Csstenersen** [andrei-tatar/node-red-contrib-nora#47]
how do we remove device's from Nora? 
i've tried to remove them from node red but their not disappearing from nora list

**Comment by rgerrans** [comment]
They don't remove immediately, it takes a little time (I don't remember the exact trigger event on the server side). Mine normally removed from the list w/i 24 hours.

**Comment by Csstenersen** [comment]
ok. then i take a look later to see if they disappear

**Comment by andrei-tatar** [comment]
>i've tried to remove them from node red but their not disappearing from nora list

If you mean the list shown here (https://node-red-google-home.herokuapp.com/) that's probably because the sync (between node-red and NORA) doesn't work properly because of invalid properties in some of the nodes. Do you have any errors in the log?

**Comment by Csstenersen** [comment]
The devices dissapered after a whilde and the case can close
