### ISSUE TITLE
Garage door

### ISSUE THREAD

**Issue by Csstenersen** [andrei-tatar/node-red-contrib-nora#48]
Not able to get garage door to work. 
in the google home app the garage door appears but i cant do anything with it. the logo shows with a cogwheel.

**Comment by rgerrans** [comment]
Garage Doors aren't supported for Touch Controls - https://developers.google.com/assistant/smarthome/develop/touch-controls#supported_device_types

**Comment by InnesB** [comment]
@Csstenersen Please refer to issue 46 which discusses garage doors and touch controls.
