### ISSUE TITLE
Cant remove groups

### ISSUE THREAD

**Issue by richard-kramer** [andrei-tatar/node-red-contrib-nora#55]
I tried out groups and now I cannot remove them. Each group always contains at least one device.

I entered something in the "Group" field of the configuration node on two different instances for testing purposes. Now I don't want to use one of the instances anymore and removed all device nodes as well as the configuration nodes but cant remove the devices from NORA. Reconnecting the service in Google Home does not help.

**Comment by andrei-tatar** [comment]
That's because there's no real way of telling if a group was actually removed or that instance is just offline for a period of time.
The simplest way is to wait at most 24h until the service restarts and they will vanish.

**Comment by richard-kramer** [comment]
Ok, good to know, the service resets itself. That totally solves my issue (i can live with a few devices too much for a day). 
A question on a similar topic: I use Nora Nodes in Subflows. Whenever I deploy node red, Google home doubles its devices and I can only solve this by relinking Nora. Has this also to do with the device caching? I assume the node IDs of subflow nodes change with every deploy and Nora wont remove the old devices because they could also just be offline.

**Comment by andrei-tatar** [comment]
> Whenever I deploy node red, Google home doubles its devices and I can only solve this by relinking Nora. Has this also to do with the device caching? I assume the node IDs of subflow nodes change with every deploy and Nora wont remove the old devices because they could also just be offline.

If node-red assigns new ids on each subflow redeploy, then that is the problem.
