### ISSUE TITLE
Impossible to link NORA in google home app

### ISSUE THREAD

**Issue by Aegnor1975** [andrei-tatar/node-red-contrib-nora#56]
Hello,
I tried many times to link NORA in google home app, by login with google (login with github doesn't work)

I have the message "linking your NORA account" and no other message, NORA is not active.
Is there a problem ?

Many thanks in advance

**Comment by andrei-tatar** [comment]
Does it work in the browser on the mobile phone?
How about if you try in the browser on the PC?

**Comment by Aegnor1975** [comment]
Hello Andrei, and thanks for your answer !
I was able to link with Google by web browser, it was blocked only in Google home app.
After about 20 times, the integration was working.
Maybe it was just a momentary problem somewhere 😉
Now I'm fighting to parse data from tasmota, but you should know I'm a newbie !
Greetings
Aegnor
