### ISSUE TITLE
HSV values in herokuapp

### ISSUE THREAD

**Issue by geoffreydemaagd** [andrei-tatar/node-red-contrib-nora#82]
Hi Andrei,

Is there something wrong with the HSL value capture when sending those values back

I'm sending these values from node red

msg.payload : Object
object
on: true
brightness: 60
color: object
spectrumHsv: object
hue: 17
saturation: 0.8
value: 1

But in herokuapp i see that the HSV values are not changed
 "type": "light",
        "brightnessControl": true,
        "turnOnWhenBrightnessChanges": true,
        "colorControl": true,
        "name": "Noord Eettafel",
        "state": {
          "online": true,
          "on": true,
          "brightness": 60,
          "color": {
            "spectrumHsv": {
              "hue": 0,
              "saturation": 0,
              "value": 1
            }

I've tried all possible capitals in the word spectrumhsv.

Many thanks

Geoffrey

**Comment by labodj** [comment]
I think it's related to: https://github.com/andrei-tatar/node-red-contrib-nora/issues/68

**Comment by geoffreydemaagd** [comment]
Related to #68
