### ISSUE TITLE
Just saying thank you. [close me]

### ISSUE THREAD

**Issue by rbm78bln** [andrei-tatar/node-red-contrib-nora#84]
Hey @andrei-tatar !

Thank you very much for your nora project. I enjoy using it at mine and my parents' home every day and just wanted to contribute to the expenses that it causes you using PayPal. You should have received it already, so don't wonder :)

Cheers Ralf

PS: Didn't know where else to leave you a message X-)

**Comment by andrei-tatar** [comment]
Thank you too, appreciate it!
