### ISSUE TITLE
Donation option

### ISSUE THREAD

**Issue by Raul-7-7** [andrei-tatar/node-red-contrib-nora#87]
Hello, 
First of all thank you so much for this AMAZING product! Node-red would not be the same for me without this ! I wanted to donate some money (very little but still that is all I can afford now) however, paypal is charging me $5 fee, is there any other option I can buy you a beer for this amazing work you have done? 
Thank you once again.

**Comment by andrei-tatar** [comment]
Hey,
I'm glad you enjoy it. 👍 
Unfortunately there is no other option yet. I did sign up for github sponsors but they don't offer it in the country I live.

Don't worry about it, just drink a beer in my name 🍻
