### ISSUE TITLE
Constant errors: "nora (0GVfg): socket connection error: user already connected"

### ISSUE THREAD

**Issue by Botched1** [andrei-tatar/node-red-contrib-nora#90]
NORA had been working fine for months for me. Now I am constantly getting this error:
"nora (0GVfg): socket connection error: user already connected"

I've tried rebooting my node-red container - same thing. I've went to the NORA login page, and can login and see my token just fine.

Any suggestions?

**Comment by IgorYbema** [comment]
Duplicate of #89

**Comment by Botched1** [comment]
Closed as duplicate.
